// frontend/src/components/library/EditBookDialog.tsx
// Edit-book dialog: staged metadata + cover save.
//
//   - Signals initialize from props once; the saved* baselines advance only
//     after a successful stage.
//   - The file input's event is typed via an intersection, not an `as` cast
//     (lint).
//   - The backdrop dismiss is the shared .backdrop-dismiss button, guarded by
//     !busy.
import { createMemo, createSignal, onCleanup, onSettled, Show } from "solid-js";
import { getCoverUrl, type BookMeta } from "~/api/client";
import { getErrorMessage } from "~/lib/errors";
import { library } from "~/lib/library";
import { toast } from "~/lib/toast";
import { trap } from "~/lib/focusTrap";
import Icon from "~/lib/Icon";
import { ImageUp, X } from "~/lib/icons";

const MAX_META_BYTES = 512;
const MAX_COVER_BYTES = 20 * 1024 * 1024;
const AUTHOR_TOO_LONG = "Author is too long (512-byte limit).";
const textEncoder = new TextEncoder();

interface Props {
  book: BookMeta;
  onclose: () => void;
}

export default function EditBookDialog(props: Props) {
  // Start from the values at open, then advance these baselines after a
  // successful metadata stage. If a following cover upload fails, the dialog
  // retries only that failed stage instead of presenting saved details as dirty.
  const [savedTitle, setSavedTitle] = createSignal(props.book.title);
  const [savedAuthor, setSavedAuthor] = createSignal(props.book.author);

  const [title, setTitle] = createSignal(props.book.title);
  const [author, setAuthor] = createSignal(props.book.author);

  const [coverFile, setCoverFile] = createSignal<File | null>(null);
  const [coverPreview, setCoverPreview] = createSignal<string | null>(null);

  const [busy, setBusy] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [coverPickError, setCoverPickError] = createSignal<string | null>(null);

  const trimmedTitle = createMemo(() => title().trim());
  const trimmedAuthor = createMemo(() => author().trim());
  const titleTooLong = createMemo(
    () => textEncoder.encode(trimmedTitle()).byteLength > MAX_META_BYTES,
  );
  const authorTooLong = createMemo(
    () => textEncoder.encode(trimmedAuthor()).byteLength > MAX_META_BYTES,
  );
  const titleError = createMemo(() =>
    trimmedTitle().length === 0
      ? "Title can’t be empty."
      : titleTooLong()
        ? "Title is too long (512-byte limit)."
        : null,
  );
  const dirty = createMemo(
    () =>
      trimmedTitle() !== savedTitle() ||
      trimmedAuthor() !== savedAuthor() ||
      coverFile() !== null,
  );
  const canSubmit = createMemo(
    () => !busy() && titleError() === null && !authorTooLong() && dirty(),
  );

  // Every message is announced from the one pre-mounted region below, never
  // from the visible paragraphs. Freshest first: a submit failure outranks the
  // field validators.
  const announcement = createMemo(
    () =>
      error() ??
      coverPickError() ??
      titleError() ??
      (authorTooLong() ? AUTHOR_TOO_LONG : null),
  );

  // Focus the field this dialog exists to edit. A ref cannot do it: refs run
  // while the node is still detached, so ref={(el) => el.focus()}
  // was a silent no-op and focusTrap's fallback took the first focusable in the
  // sheet -- the header close button, where Enter dismisses. Deferring one
  // microtask lands after the trap's own queueMicrotask; if this runs first
  // instead, the trap's !node.contains(activeElement) guard stands down.
  let titleEl: HTMLInputElement | undefined;
  onSettled(() => {
    queueMicrotask(() => titleEl?.focus());
  });

  // The chosen file's object URL is revoked when replaced (below) and on
  // destroy, so a dialog opened/closed repeatedly doesn't leak blob URLs.
  onCleanup(() => {
    const preview = coverPreview();
    if (preview) URL.revokeObjectURL(preview);
  });

  function onCoverPick(e: Event & { currentTarget: HTMLInputElement }): void {
    const input = e.currentTarget;
    const file = input.files?.[0] ?? null;
    if (!file) return;
    setError(null);
    // A rejected pick leaves an already-staged cover alone: discarding it threw
    // away a good selection and said only "choose a JPEG", with the preview
    // silently reverting to the book's existing cover. Clearing the input's
    // value is enough to let the same file be re-picked.
    if (!/^image\/(jpeg|png|webp)$/.test(file.type)) {
      setCoverPickError("Choose a JPEG, PNG, or WebP image.");
      input.value = "";
      return;
    }
    if (file.size > MAX_COVER_BYTES) {
      setCoverPickError("Choose an image no larger than 20 MB.");
      input.value = "";
      return;
    }
    setCoverPickError(null);
    const preview = coverPreview();
    if (preview) URL.revokeObjectURL(preview);
    setCoverFile(file);
    setCoverPreview(URL.createObjectURL(file));
  }

  const currentCover = createMemo(
    () =>
      coverPreview() ??
      (props.book.hasCover
        ? getCoverUrl(props.book.id, props.book.updatedAt)
        : null),
  );

  async function submit(e: Event): Promise<void> {
    e.preventDefault();
    if (!canSubmit()) return;

    // Freeze one coherent submission. Controls are disabled below while busy,
    // but these snapshots also prevent a late file-picker event from changing
    // which values an already-running save commits.
    const submittedTitle = trimmedTitle();
    const submittedAuthor = trimmedAuthor();
    const submittedCover = coverFile();
    let savedDetailsThisAttempt = false;

    setBusy(true);
    setError(null);
    setCoverPickError(null);
    try {
      const patch: { title?: string; author?: string } = {};
      if (submittedTitle !== savedTitle()) patch.title = submittedTitle;
      if (submittedAuthor !== savedAuthor()) patch.author = submittedAuthor;
      if (patch.title !== undefined || patch.author !== undefined) {
        await library.editMetadata(props.book.id, patch);
        setSavedTitle(submittedTitle);
        setSavedAuthor(submittedAuthor);
        savedDetailsThisAttempt = true;
      }
      if (submittedCover) {
        await library.replaceCover(props.book.id, submittedCover);
      }
      toast.show("Saved changes");
      props.onclose();
    } catch (err) {
      const message = getErrorMessage(err, "Something went wrong.");
      setError(
        savedDetailsThisAttempt && submittedCover
          ? `Book details were saved, but the cover could not be replaced: ${message}`
          : message,
      );
      setBusy(false);
    }
  }

  function onKeydown(e: KeyboardEvent): void {
    // An IME uses Escape to abandon a composition, and capture at window beats
    // the field, so without this the dialog closed and dropped the edit
    // (BookmarksPanel, SearchPanel and TocPanel guard the same way).
    if (e.isComposing) return;
    if (e.key === "Escape") {
      e.preventDefault();
      // Consume so the reader/library window key handlers don't also act on it.
      e.stopImmediatePropagation();
      if (!busy()) props.onclose();
    }
  }

  // Capture phase: the dialog mounts after the page's own window key
  // listeners, so a bubble listener here runs last and can't pre-empt them;
  // capture runs first regardless of registration order. Attached only while
  // the dialog is mounted.
  onSettled(() => {
    window.addEventListener("keydown", onKeydown, true);
    return () => window.removeEventListener("keydown", onKeydown, true);
  });

  return (
    <div class="eb-overlay" role="presentation">
      <button
        type="button"
        class="backdrop-dismiss"
        aria-label="Close"
        tabindex="-1"
        onClick={() => {
          if (!busy()) props.onclose();
        }}
      />
      {/* div+role kept over a native <dialog>: visual parity with the established design is the port's contract. */}
      <div
        class="eb-sheet"
        role="dialog"
        tabindex="-1"
        aria-modal="true"
        aria-label="Edit book"
        ref={trap()}
      >
        <header>
          <div class="eb-head-text">
            <p class="eyebrow">Library</p>
            <h2 class="display">Edit book</h2>
          </div>
          <button
            class="icon-btn press eb-close"
            aria-label="Close"
            onClick={() => props.onclose()}
            disabled={busy()}
          >
            <Icon icon={X} size={18} labelFromParent />
          </button>
        </header>

        <form
          onSubmit={(e) => void submit(e)}
          aria-busy={busy() ? "true" : "false"}
        >
          <div class="eb-cover-row">
            <div class="eb-cover-preview">
              <Show
                when={currentCover()}
                fallback={
                  <div class="eb-cover-placeholder display">{title()}</div>
                }
              >
                {(src) => <img src={src()} alt="" />}
              </Show>
            </div>
            <div class="eb-cover-actions">
              <label
                class={["btn-ghost press eb-file-btn", { disabled: busy() }]}
              >
                <Icon icon={ImageUp} size={16} decorative />
                {coverFile() ? "Change image" : "Replace cover"}
                <input
                  class="eb-file-input"
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  aria-label={
                    coverFile() ? "Change cover image" : "Replace cover"
                  }
                  aria-invalid={coverPickError() !== null ? "true" : "false"}
                  aria-describedby={
                    coverPickError()
                      ? "cover-hint cover-pick-error"
                      : "cover-hint"
                  }
                  disabled={busy()}
                  onChange={onCoverPick}
                />
              </label>
              <Show when={coverFile()}>
                {(f) => (
                  <p class="eb-cover-name" title={f().name}>
                    {f().name}
                  </p>
                )}
              </Show>
              <p class="eb-hint" id="cover-hint">
                JPEG, PNG, or WebP · up to 20 MB · resized on save.
              </p>
              <Show when={coverPickError()}>
                {(message) => (
                  <p class="eb-error" id="cover-pick-error">
                    {message()}
                  </p>
                )}
              </Show>
            </div>
          </div>

          <label class="eb-frow">
            <span class="eb-lbl">Title</span>
            <input
              class="field"
              type="text"
              value={title()}
              onInput={(e) => setTitle(e.currentTarget.value)}
              maxlength="512"
              autocomplete="off"
              aria-invalid={titleError() !== null ? "true" : "false"}
              aria-describedby={titleError() ? "book-title-error" : undefined}
              readonly={busy()}
              aria-disabled={busy() ? "true" : "false"}
              ref={(el) => (titleEl = el)}
            />
          </label>
          {/* Always mounted and hidden when clean, so aria-invalid, the
              describedby link, and the error text can never disagree. A book
              with no title -- which the importer allows and PATCH then
              rejects -- is the case that needs it: the error must vanish the
              moment the field validates. */}
          <p
            class="eb-note"
            id="book-title-error"
            hidden={titleError() === null}
          >
            {titleError() ?? ""}
          </p>

          <label class="eb-frow">
            <span class="eb-lbl">Author</span>
            <input
              class="field"
              type="text"
              value={author()}
              onInput={(e) => setAuthor(e.currentTarget.value)}
              maxlength="512"
              autocomplete="off"
              aria-invalid={authorTooLong() ? "true" : "false"}
              aria-describedby={
                authorTooLong() ? "book-author-error" : undefined
              }
              readonly={busy()}
              aria-disabled={busy() ? "true" : "false"}
            />
          </label>
          <p class="eb-note" id="book-author-error" hidden={!authorTooLong()}>
            {AUTHOR_TOO_LONG}
          </p>

          <Show when={error()}>
            {(message) => <p class="eb-error">{message()}</p>}
          </Show>

          {/* Pre-mounted live region. Every visible message above is inserted
              in the same tick as its text, which NVDA and JAWS do not announce
              (WCAG 4.1.3) -- this region exists from first paint and only
              its text changes, so the paragraphs carry no role="alert". */}
          <p class="sr-only" role="alert">
            {announcement() ?? ""}
          </p>

          <div class="eb-actions">
            <button
              type="button"
              class="btn-ghost press"
              onClick={() => props.onclose()}
              disabled={busy()}
            >
              Cancel
            </button>
            {/* aria-disabled, not disabled: a real disabled attribute blurs
                whatever holds focus the moment the save starts, which dropped
                the keyboard user out of the dialog for the whole request and
                left them nowhere on failure. submit() holds the guard. */}
            <button
              type="submit"
              class="btn press eb-save"
              aria-disabled={!canSubmit() ? "true" : "false"}
            >
              {busy() ? "Saving…" : "Save changes"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// frontend/src/components/library/EditBookDialog.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { ApiError, getCoverUrl, type BookMeta } from "~/api/client";
  import { library } from "~/lib/library.svelte";
  import { toast } from "~/lib/toast.svelte";
  import { focusTrap } from "~/lib/focusTrap";
  import Icon from "~/lib/Icon.svelte";
  import { X, ImageUp } from "@lucide/svelte";

  interface Props {
    book: BookMeta;
    onclose: () => void;
  }
  let { book, onclose }: Props = $props();

  const MAX_META_BYTES = 512;
  const MAX_COVER_BYTES = 20 * 1024 * 1024;
  const textEncoder = new TextEncoder();

  // Start from the values at open, then advance these baselines after a
  // successful metadata stage. If a following cover upload fails, the dialog
  // retries only that failed stage instead of presenting saved details as dirty.
  // svelte-ignore state_referenced_locally
  let savedTitle = $state(book.title);
  // svelte-ignore state_referenced_locally
  let savedAuthor = $state(book.author);

  // svelte-ignore state_referenced_locally
  let title = $state(book.title);
  // svelte-ignore state_referenced_locally
  let author = $state(book.author);

  let coverFile = $state<File | null>(null);
  let coverPreview = $state<string | null>(null);

  let busy = $state(false);
  let error = $state<string | null>(null);
  let coverPickError = $state<string | null>(null);

  const trimmedTitle = $derived(title.trim());
  const trimmedAuthor = $derived(author.trim());
  const titleTooLong = $derived(
    textEncoder.encode(trimmedTitle).byteLength > MAX_META_BYTES,
  );
  const authorTooLong = $derived(
    textEncoder.encode(trimmedAuthor).byteLength > MAX_META_BYTES,
  );
  const titleError = $derived(
    trimmedTitle.length === 0
      ? "Title can’t be empty."
      : titleTooLong
        ? "Title is too long (512-byte limit)."
        : null,
  );
  const dirty = $derived(
    trimmedTitle !== savedTitle ||
      trimmedAuthor !== savedAuthor ||
      coverFile !== null,
  );
  const canSubmit = $derived(
    !busy && titleError === null && !authorTooLong && dirty,
  );

  // The chosen file's object URL is revoked when replaced (below) and on
  // destroy, so a dialog opened/closed repeatedly doesn't leak blob URLs.
  onDestroy(() => {
    if (coverPreview) URL.revokeObjectURL(coverPreview);
  });

  function clearCoverSelection(): void {
    if (coverPreview) URL.revokeObjectURL(coverPreview);
    coverFile = null;
    coverPreview = null;
  }

  function onCoverPick(e: Event): void {
    const input = e.currentTarget as HTMLInputElement;
    const file = input.files?.[0] ?? null;
    if (!file) return;
    error = null;
    if (!/^image\/(jpeg|png|webp)$/.test(file.type)) {
      clearCoverSelection();
      coverPickError = "Choose a JPEG, PNG, or WebP image.";
      input.value = "";
      return;
    }
    if (file.size > MAX_COVER_BYTES) {
      clearCoverSelection();
      coverPickError = "Choose an image no larger than 20 MB.";
      input.value = "";
      return;
    }
    coverPickError = null;
    if (coverPreview) URL.revokeObjectURL(coverPreview);
    coverFile = file;
    coverPreview = URL.createObjectURL(file);
  }

  const currentCover = $derived(
    coverPreview ??
      (book.hasCover ? getCoverUrl(book.id, book.updatedAt) : null),
  );

  async function submit(e: Event): Promise<void> {
    e.preventDefault();
    if (!canSubmit) return;

    // Freeze one coherent submission. Controls are disabled below while busy,
    // but these snapshots also prevent a late file-picker event from changing
    // which values an already-running save commits.
    const submittedTitle = trimmedTitle;
    const submittedAuthor = trimmedAuthor;
    const submittedCover = coverFile;
    let savedDetailsThisAttempt = false;

    busy = true;
    error = null;
    coverPickError = null;
    try {
      const patch: { title?: string; author?: string } = {};
      if (submittedTitle !== savedTitle) patch.title = submittedTitle;
      if (submittedAuthor !== savedAuthor) patch.author = submittedAuthor;
      if (patch.title !== undefined || patch.author !== undefined) {
        await library.editMetadata(book.id, patch);
        savedTitle = submittedTitle;
        savedAuthor = submittedAuthor;
        savedDetailsThisAttempt = true;
      }
      if (submittedCover) await library.replaceCover(book.id, submittedCover);
      toast.show("Saved changes");
      onclose();
    } catch (err) {
      const message =
        err instanceof ApiError ? err.message : "Something went wrong.";
      error =
        savedDetailsThisAttempt && submittedCover
          ? `Book details were saved, but the cover could not be replaced: ${message}`
          : message;
      busy = false;
    }
  }

  function onKeydown(e: KeyboardEvent): void {
    if (e.key === "Escape") {
      e.preventDefault();
      // Consume so the reader/library window key handlers don't also act on it.
      e.stopImmediatePropagation();
      if (!busy) onclose();
    }
  }
</script>

<!-- Capture phase: the dialog mounts after the page's own window key
     listeners, so a bubble listener here runs last and can't pre-empt them;
     capture runs first regardless of registration order. -->
<svelte:window onkeydowncapture={onKeydown} />

<div class="overlay" role="presentation" onclick={() => !busy && onclose()}>
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="sheet"
    role="dialog"
    tabindex="-1"
    aria-modal="true"
    aria-label="Edit book"
    onclick={(e) => e.stopPropagation()}
    {@attach focusTrap}
  >
    <header>
      <div class="head-text">
        <p class="eyebrow">Library</p>
        <h2 class="display">Edit book</h2>
      </div>
      <button
        class="icon-btn press close"
        aria-label="Close"
        onclick={onclose}
        disabled={busy}
      >
        <Icon icon={X} size={18} />
      </button>
    </header>

    <form onsubmit={submit} aria-busy={busy}>
      <div class="cover-row">
        <div class="cover-preview">
          {#if currentCover}
            <img src={currentCover} alt="" />
          {:else}
            <div class="cover-placeholder display">{title}</div>
          {/if}
        </div>
        <div class="cover-actions">
          <label class="btn-ghost press file-btn" class:disabled={busy}>
            <Icon icon={ImageUp} size={16} />
            {coverFile ? "Change image" : "Replace cover"}
            <input
              class="file-input"
              type="file"
              accept="image/jpeg,image/png,image/webp"
              aria-label={coverFile ? "Change cover image" : "Replace cover"}
              aria-invalid={coverPickError !== null}
              aria-describedby={coverPickError
                ? "cover-hint cover-pick-error"
                : "cover-hint"}
              disabled={busy}
              onchange={onCoverPick}
            />
          </label>
          {#if coverFile}
            <p class="cover-name" title={coverFile.name}>{coverFile.name}</p>
          {/if}
          <p class="hint" id="cover-hint">
            JPEG, PNG, or WebP · up to 20 MB · resized on save.
          </p>
          {#if coverPickError}
            <p class="error" id="cover-pick-error" role="alert">
              {coverPickError}
            </p>
          {/if}
        </div>
      </div>

      <label class="frow">
        <span class="lbl">Title</span>
        <input
          class="field"
          type="text"
          bind:value={title}
          maxlength="512"
          autocomplete="off"
          aria-invalid={titleError !== null}
          aria-describedby={titleError ? "book-title-error" : undefined}
          disabled={busy}
          {@attach (el) => (el as HTMLInputElement).focus()}
        />
      </label>
      {#if titleError}
        <p class="note" id="book-title-error" role="alert">{titleError}</p>
      {/if}

      <label class="frow">
        <span class="lbl">Author</span>
        <input
          class="field"
          type="text"
          bind:value={author}
          maxlength="512"
          autocomplete="off"
          aria-invalid={authorTooLong}
          aria-describedby={authorTooLong ? "book-author-error" : undefined}
          disabled={busy}
        />
      </label>
      {#if authorTooLong}
        <p class="note" id="book-author-error" role="alert">
          Author is too long (512-byte limit).
        </p>
      {/if}

      {#if error}
        <p class="error" role="alert">{error}</p>
      {/if}

      <div class="actions">
        <button
          type="button"
          class="btn-ghost press"
          onclick={onclose}
          disabled={busy}
        >
          Cancel
        </button>
        <button type="submit" class="btn press" disabled={!canSubmit}>
          {busy ? "Saving…" : "Save changes"}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    inset: 0;
    z-index: 60;
    display: grid;
    place-items: center;
    padding: var(--sp-6);
    background: var(--veil);
    -webkit-backdrop-filter: blur(4px);
    backdrop-filter: blur(4px);
    animation: app-overlay-in var(--dur) var(--ease-out);
  }
  .sheet {
    width: min(30rem, 100%);
    max-height: calc(100vh - var(--sp-12));
    overflow-y: auto;
    background: var(--raised);
    border: 1px solid var(--hairline);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-3);
    animation: app-sheet-in var(--dur-slow) var(--ease-out);
  }
  header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: var(--sp-3);
    padding: var(--sp-5) var(--sp-5) var(--sp-3);
    border-bottom: 1px solid var(--hairline);
    position: sticky;
    top: 0;
    background: var(--raised);
    z-index: 1;
  }
  .head-text {
    display: flex;
    flex-direction: column;
    gap: var(--sp-1);
  }
  .head-text .eyebrow {
    margin: 0;
  }
  h2 {
    margin: 0;
    font-size: var(--text-xl);
    font-weight: 540;
    line-height: var(--lh-tight);
  }
  .close {
    flex-shrink: 0;
  }
  form {
    display: flex;
    flex-direction: column;
    gap: var(--sp-4);
    padding: var(--sp-5);
  }

  .cover-row {
    display: flex;
    gap: var(--sp-4);
    align-items: flex-start;
  }
  .cover-preview {
    flex-shrink: 0;
    width: 6rem;
    aspect-ratio: 2 / 3;
    border-radius: 3px 7px 7px 3px;
    overflow: hidden;
    background: var(--surface);
    box-shadow: var(--shadow-1);
  }
  .cover-preview img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
  }
  .cover-placeholder {
    width: 100%;
    height: 100%;
    display: grid;
    place-items: center;
    padding: var(--sp-2);
    text-align: center;
    font-style: italic;
    font-size: var(--text-xs);
    color: var(--muted);
    background: linear-gradient(
      160deg,
      var(--surface),
      color-mix(in srgb, var(--accent) 10%, transparent)
    );
  }
  .cover-actions {
    display: flex;
    flex-direction: column;
    gap: var(--sp-2);
    min-width: 0;
  }
  .file-btn {
    position: relative;
    cursor: pointer;
    align-self: flex-start;
    overflow: hidden;
  }
  .file-btn:has(.file-input:focus-visible) {
    box-shadow: var(--focus);
  }
  .file-btn.disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .file-input {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    cursor: pointer;
  }
  .file-input:disabled {
    cursor: not-allowed;
  }
  .cover-name {
    margin: 0;
    font-size: var(--text-xs);
    color: var(--fg);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    max-width: 14rem;
  }
  .hint {
    margin: 0;
    font-size: var(--text-xs);
    color: var(--muted);
    line-height: 1.4;
  }

  .frow {
    display: flex;
    flex-direction: column;
    gap: var(--sp-1);
  }
  .lbl {
    font-size: var(--text-xs);
    font-weight: 640;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--muted);
  }
  .frow input {
    height: 2.5rem;
  }
  .frow input:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .error {
    margin: 0;
    color: var(--danger);
    font-size: var(--text-sm);
  }
  .note {
    margin: 0;
    margin-top: calc(var(--sp-3) * -1);
    color: var(--danger);
    font-size: var(--text-xs);
  }
  .actions {
    display: flex;
    justify-content: flex-end;
    gap: var(--sp-2);
    margin-top: var(--sp-1);
    padding-top: var(--sp-4);
    border-top: 1px solid var(--hairline);
  }
</style>
