// frontend/src/components/library/ShareDialog.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import {
    ApiError,
    getDownloadUrl,
    uploadToGofile,
    type BookMeta,
  } from "~/api/client";
  import { toast } from "~/lib/toast.svelte";
  import { focusTrap } from "~/lib/focusTrap";
  import Icon from "~/lib/Icon.svelte";
  import { X, UploadCloud, Copy, Check, Download } from "@lucide/svelte";

  interface Props {
    book: BookMeta;
    onclose: () => void;
  }
  let { book, onclose }: Props = $props();

  // Direct local download: a same-origin <a download> hitting the file endpoint
  // streams the .epub with Content-Disposition: attachment, so the browser
  // saves it without any JS. The download attribute is just a filename hint;
  // the server's Content-Disposition is authoritative.
  const downloadUrl = $derived(getDownloadUrl(book.id));
  const downloadName = $derived(`${book.title || "book"}.epub`);

  let busy = $state(false);
  let url = $state<string | null>(null);
  let error = $state<string | null>(null);
  let copied = $state(false);
  let uploadController: AbortController | null = null;
  let copiedResetTimer: ReturnType<typeof setTimeout> | null = null;

  async function upload(): Promise<void> {
    if (busy) return;
    const controller = new AbortController();
    uploadController = controller;
    busy = true;
    error = null;
    try {
      const { downloadPage } = await uploadToGofile(book.id, controller.signal);
      url = downloadPage;
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") return;
      error =
        err instanceof ApiError ? err.message : "Upload to gofile failed.";
    } finally {
      if (uploadController === controller) {
        uploadController = null;
        busy = false;
      }
    }
  }

  async function copyLink(): Promise<void> {
    if (!url) return;
    try {
      await navigator.clipboard.writeText(url);
      copied = true;
      toast.show("Link copied");
      if (copiedResetTimer !== null) clearTimeout(copiedResetTimer);
      copiedResetTimer = setTimeout(() => {
        copied = false;
        copiedResetTimer = null;
      }, 1500);
    } catch {
      toast.show("Could not copy link");
    }
  }

  function close(): void {
    uploadController?.abort();
    onclose();
  }

  onDestroy(() => {
    uploadController?.abort();
    if (copiedResetTimer !== null) clearTimeout(copiedResetTimer);
  });

  function onKeydown(e: KeyboardEvent): void {
    if (e.key === "Escape") {
      e.preventDefault();
      // Consume so the reader/library window key handlers don't also act on it.
      e.stopImmediatePropagation();
      close();
    }
  }
</script>

<!-- Capture phase: the dialog mounts after the page's own window key
     listeners, so a bubble listener here runs last and can't pre-empt them;
     capture runs first regardless of registration order. -->
<svelte:window onkeydowncapture={onKeydown} />

<div class="overlay" role="presentation" onclick={close}>
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    class="sheet"
    role="dialog"
    tabindex="-1"
    aria-modal="true"
    aria-label="Share book"
    aria-busy={busy}
    onclick={(e) => e.stopPropagation()}
    {@attach focusTrap}
  >
    <header>
      <div class="head-text">
        <p class="eyebrow">Share</p>
        <h2 class="display" title={book.title}>“{book.title}”</h2>
      </div>
      <button
        class="icon-btn press close"
        aria-label={busy ? "Cancel upload and close" : "Close"}
        onclick={close}
      >
        <Icon icon={X} size={18} />
      </button>
    </header>

    <div class="body">
      <p class="lead">Download the original .epub to this device.</p>
      <a
        class="btn-ghost press download-btn"
        href={downloadUrl}
        download={downloadName}
      >
        <Icon icon={Download} size={16} />
        Download EPUB
      </a>

      <hr class="divider" />

      <p class="lead">
        Or upload the .epub to gofile.io and get a shareable link.
      </p>
      <p class="hint">
        Anonymous upload — anyone with the link can download the file.
      </p>

      <button class="btn press upload-btn" onclick={upload} disabled={busy}>
        <Icon icon={UploadCloud} size={16} />
        {busy ? "Uploading…" : url ? "Upload again" : "Upload to gofile"}
      </button>

      {#if url}
        <div class="result">
          <a href={url} target="_blank" rel="noopener noreferrer">{url}</a>
          <button
            type="button"
            class="icon-btn press copy-btn"
            aria-label={copied ? "Link copied" : "Copy link"}
            title={copied ? "Link copied" : "Copy link"}
            onclick={copyLink}
          >
            <Icon icon={copied ? Check : Copy} size={15} />
          </button>
        </div>
      {/if}
      {#if error}
        <p class="error" role="alert">{error}</p>
      {/if}
    </div>
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    inset: 0;
    z-index: 60;
    display: grid;
    place-items: center;
    padding: var(--sp-6);
    background: var(--veil);
    -webkit-backdrop-filter: blur(4px);
    backdrop-filter: blur(4px);
    animation: app-overlay-in var(--dur) var(--ease-out);
  }
  .sheet {
    width: min(28rem, 100%);
    max-height: calc(100dvh - var(--sp-12));
    overflow-y: auto;
    background: var(--raised);
    border: 1px solid var(--hairline);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-3);
    animation: app-sheet-in var(--dur-slow) var(--ease-out);
  }
  header {
    position: sticky;
    top: 0;
    z-index: 1;
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: var(--sp-3);
    padding: var(--sp-5) var(--sp-5) var(--sp-3);
    border-bottom: 1px solid var(--hairline);
    background: var(--raised);
  }
  .head-text {
    display: flex;
    flex-direction: column;
    gap: var(--sp-1);
    min-width: 0;
  }
  .head-text .eyebrow {
    margin: 0;
  }
  h2 {
    margin: 0;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: var(--text-lg);
    font-style: italic;
    font-weight: 520;
    line-height: var(--lh-snug);
  }
  .close {
    flex-shrink: 0;
  }
  .body {
    display: flex;
    flex-direction: column;
    gap: var(--sp-3);
    padding: var(--sp-5);
  }
  .lead {
    margin: 0;
    font-size: var(--text-sm);
    color: var(--fg);
  }
  .hint {
    margin: 0;
    font-size: var(--text-xs);
    color: var(--muted);
    line-height: 1.4;
  }
  .result {
    display: flex;
    align-items: center;
    gap: var(--sp-2);
    padding: var(--sp-2);
    border-radius: var(--radius);
    background: var(--surface);
    border: 1px solid var(--hairline);
    animation: app-sheet-in var(--dur-slow) var(--ease-out);
  }
  .result a {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    color: var(--accent-ink);
    font-size: var(--text-xs);
    font-weight: 560;
  }
  .copy-btn {
    width: 1.9rem;
    height: 1.9rem;
  }
  .error {
    margin: 0;
    padding: var(--sp-2) var(--sp-3);
    border-radius: var(--radius);
    background: var(--danger-surface);
    color: var(--danger-surface-fg);
    font-size: var(--text-sm);
    overflow-wrap: anywhere;
  }
  .download-btn,
  .upload-btn {
    align-self: flex-start;
    text-decoration: none;
  }
  .divider {
    align-self: stretch;
    width: 100%;
    margin: var(--sp-2) 0;
    border: none;
    border-top: 1px solid var(--hairline);
    position: relative;
  }
</style>

// frontend/src/components/library/ShareDialog.tsx
// Share dialog: direct .epub download, or anonymous gofile upload for a
// shareable link.
//
// Solid 2.0 notes:
//   - ref={trap()} — see focusTrap.ts for why the two-phase factory is
//     required; the abort controller and timers are plain (non-reactive)
//     vars.
//   - The backdrop dismiss is the shared .backdrop-dismiss button instead of
//     the sheet stopPropagation trick, which jsx-a11y rejects.
import { createMemo, createSignal, onCleanup, onSettled, Show } from "solid-js";
import { getDownloadUrl, uploadToGofile, type BookMeta } from "~/api/client";
import { getErrorMessage } from "~/lib/errors";
import { toast } from "~/lib/toast";
import { trap } from "~/lib/focusTrap";
import Icon from "~/lib/Icon";
import { Check, Copy, Download, UploadCloud, X } from "~/lib/icons";

interface Props {
  book: BookMeta;
  onclose: () => void;
}

export default function ShareDialog(props: Props) {
  // Direct local download: a same-origin <a download> hitting the file
  // endpoint streams the .epub with Content-Disposition: attachment, so the
  // browser saves it without any JS. The download attribute is just a
  // filename hint; the server's Content-Disposition is authoritative.
  const downloadUrl = createMemo(() => getDownloadUrl(props.book.id));
  const downloadName = createMemo(() => `${props.book.title || "book"}.epub`);

  const [busy, setBusy] = createSignal(false);
  const [url, setUrl] = createSignal<string | null>(null);
  const [error, setError] = createSignal<string | null>(null);
  const [copied, setCopied] = createSignal(false);
  let uploadController: AbortController | null = null;
  let copiedResetTimer: ReturnType<typeof setTimeout> | null = null;

  async function upload(): Promise<void> {
    if (busy()) return;
    const controller = new AbortController();
    uploadController = controller;
    setBusy(true);
    setError(null);
    try {
      const { downloadPage } = await uploadToGofile(
        props.book.id,
        controller.signal,
      );
      setUrl(downloadPage);
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") return;
      setError(getErrorMessage(err, "Upload to gofile failed."));
    } finally {
      if (uploadController === controller) {
        uploadController = null;
        setBusy(false);
      }
    }
  }

  async function copyLink(): Promise<void> {
    const link = url();
    if (!link) return;
    try {
      await navigator.clipboard.writeText(link);
      setCopied(true);
      toast.show("Link copied");
      if (copiedResetTimer !== null) clearTimeout(copiedResetTimer);
      copiedResetTimer = setTimeout(() => {
        setCopied(false);
        copiedResetTimer = null;
      }, 1500);
    } catch {
      toast.show("Could not copy link");
    }
  }

  function close(): void {
    uploadController?.abort();
    props.onclose();
  }

  onCleanup(() => {
    uploadController?.abort();
    if (copiedResetTimer !== null) clearTimeout(copiedResetTimer);
  });

  // Focus the download action, the control this dialog exists for. A ref
  // cannot do it: refs run while the node is still detached, so
  // a self-focusing ref would be a silent no-op and focusTrap's fallback
  // would take the first focusable in the sheet -- the header close button,
  // where Enter dismisses. Deferring one
  // microtask lands after the trap's own queueMicrotask; if this runs first
  // instead, the trap's !node.contains(activeElement) guard stands down.
  let downloadEl: HTMLAnchorElement | undefined;
  onSettled(() => {
    queueMicrotask(() => downloadEl?.focus());
  });

  function onKeydown(e: KeyboardEvent): void {
    // An IME uses Escape to abandon a composition, and capture at window beats
    // the focused control, so without this guard the dialog closed
    // mid-composition (EditBookDialog, BookmarksPanel, SearchPanel and
    // TocPanel guard the same way).
    if (e.isComposing) return;
    if (e.key === "Escape") {
      e.preventDefault();
      // Consume so the reader/library window key handlers don't also act on
      // it.
      e.stopImmediatePropagation();
      close();
    }
  }

  // Capture phase: the dialog mounts after the page's own window key
  // listeners, so a bubble listener here runs last and can't pre-empt them;
  // capture runs first regardless of registration order. Attached only while
  // the dialog is mounted.
  onSettled(() => {
    window.addEventListener("keydown", onKeydown, true);
    return () => window.removeEventListener("keydown", onKeydown, true);
  });

  return (
    <div class="sd-overlay" role="presentation">
      <button
        type="button"
        class="backdrop-dismiss"
        aria-label="Close"
        tabindex="-1"
        onClick={close}
      />
      {/* eslint-disable jsx-a11y/prefer-tag-over-role -- div+role kept over a native <dialog>: visual parity with the Svelte original is the port's contract. */}
      <div
        class="sd-sheet"
        role="dialog"
        tabindex="-1"
        aria-modal="true"
        aria-label="Share book"
        aria-busy={busy() ? "true" : "false"}
        ref={trap()}
      >
        <header>
          <div class="sd-head-text">
            <p class="eyebrow">Share</p>
            <h2 class="display" title={props.book.title}>
              “{props.book.title}”
            </h2>
          </div>
          <button
            class="icon-btn press sd-close"
            aria-label={busy() ? "Cancel upload and close" : "Close"}
            onClick={close}
          >
            <Icon icon={X} size={18} labelFromParent />
          </button>
        </header>

        <div class="sd-body">
          <p class="sd-lead">Download the original .epub to this device.</p>
          <a
            class="btn-ghost press sd-download-btn"
            href={downloadUrl()}
            download={downloadName()}
            ref={(el) => (downloadEl = el)}
          >
            <Icon icon={Download} size={16} decorative />
            Download EPUB
          </a>

          <hr class="sd-divider" />

          <p class="sd-lead">
            Or upload the .epub to gofile.io and get a shareable link.
          </p>
          <p class="sd-hint">
            Anonymous upload — anyone with the link can download the file.
          </p>

          {/* aria-disabled, not disabled: an upload can run for the whole
              gofile timeout (30 minutes), and a real disabled attribute blurs
              the button the moment it is pressed, dropping the keyboard user
              out of the dialog for the duration. upload() entry-guards the
              busy state, so the attribute only has to say so. */}
          <button
            class="btn press sd-upload-btn"
            onClick={() => void upload()}
            aria-disabled={busy() ? "true" : "false"}
          >
            <Icon icon={UploadCloud} size={16} decorative />
            {busy()
              ? "Uploading…"
              : url()
                ? "Upload again"
                : "Upload to gofile"}
          </button>

          <Show when={url()}>
            {(link) => (
              <div class="sd-result">
                <a href={link()} target="_blank" rel="noopener noreferrer">
                  {link()}
                </a>
                <button
                  type="button"
                  class="icon-btn press sd-copy-btn"
                  aria-label={copied() ? "Link copied" : "Copy link"}
                  title={copied() ? "Link copied" : "Copy link"}
                  onClick={() => void copyLink()}
                >
                  <Icon
                    icon={copied() ? Check : Copy}
                    size={15}
                    labelFromParent
                  />
                </button>
              </div>
            )}
          </Show>
          <Show when={error()}>
            {(message) => <p class="sd-error">{message()}</p>}
          </Show>

          {/* Pre-mounted live region, same as EditBookDialog/ProfileDialog:
              the visible error above is inserted in the same tick as its
              text, which NVDA and JAWS do not announce (WCAG 4.1.3) --
              this region exists from first paint and only its text changes,
              so the paragraph carries no role="alert". */}
          <p class="sr-only" role="alert">
            {error() ?? ""}
          </p>
        </div>
      </div>
      {/* eslint-enable jsx-a11y/prefer-tag-over-role */}
    </div>
  );
}
